title: Kelly Hsiao-Ching Su
description:
show_downloads: true
google_analytics: true
theme: jekyll-theme-leap-day
default:
      resume: ./Hsiao-Ching_Su_resume.pdf
github:
      is_project_page: true
      owner_url: https://github.com/CApopsicle
      owner_name: CApopsicle